package makao.view.actions;

public enum MakaoActions {
	OPEN_CONFIG_DIALOG,
	CLOSE_CONFIG_DIALOG,
	START_LOCAL_SERVER,
	STOP_STOP_SERVER,
	CONNECT_CLIENT,
	DISCONNECT_CLIENT,
	SERVER_START_GAME,
	GAME_END_MY_TURN,
	GAME_SEND_MESSAGE_TO_ALL;
}
