package makao.view.actions;

public enum MakaoActions {
	OPEN_CONFIG_DIALOG, //Otwarcie okna konfiguracyjnego
	CLOSE_CONFIG_DIALOG, //Zamkni«cie okna konfiguracyjnego
	START_LOCAL_SERVER, //Uruchomienie servera
	STOP_STOP_SERVER, //Zatrzymanie servera
	CONNECT_CLIENT,
	DISCONNECT_CLIENT,
	SERVER_START_GAME,
	SHOW_SELECT_CARD_NUMBER_DIALOG,
	SHOW_SELECT_CARD_COLOR_DIALOG,
	GAME_END_MY_TURN,
	GAME_MAKAO,
	GAME_SEND_MESSAGE_TO_ALL,
	GAME_SELECT_CARD,
	GAME_REQUIRE_NUMBER,
	GAME_REQUIRE_COLOR,
	GAME_TAKE_NEXT_CARD,
	EXIT_APPLICATION;
}
